spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          # Because for some reason we cant use multiline statements in import.sql by default, see https://stackoverflow.com/a/32955642/3257988